version: "1.0"
info:
  model: int-scaffold
packages:
- name: NawazCAProject
  gitServerName: NawazGH
  gitUrl: https://github.com/nawajish-laskar-IBM
  gitUsername: nawajish-laskar-IBM
  gitBranch: main
